In [1]:
%run  "./env_setup.py"

Connecting to 'postgresql://admin:***@localhost:5433/churn_db'

User:  barrechee
Database:  postgresql://admin:secret@localhost:5433/churn_db

In [2]:
import pandas as pd

In [3]:
#url = "https://storage.googleapis.com/jvelare-public/bq-results-20260211-093843-1770799837095"
#customer_data = pd.read_csv(url)
#customer_data.to_csv("data/lake/customer_data.csv", index=False)

In [4]:
customer_data = pd.read_csv("data/lake/customer_data.csv")
new_customer = pd.read_csv("data/lake/nuevos_clientes.csv")
cost = pd.read_csv("data/lake/costes.csv")

In [5]:
#print(customer_data.columns)
#print(new_customer.columns)
#print(cost.columns)

In [ ]:
%%sql
DROP TABLE IF EXISTS new_sales CASCADE;
DROP TABLE IF EXISTS sales CASCADE;
DROP TABLE IF EXISTS model_costs CASCADE;
DROP TABLE IF EXISTS stores CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS customers CASCADE;

CREATE TABLE customers (
    customer_id INTEGER PRIMARY KEY,
    genero VARCHAR(20),
    codigo_postal VARCHAR(20),
    edad INTEGER,
    renta_media_estimada NUMERIC(12,2),
    status_social VARCHAR(50)
);

CREATE TABLE products (
    id_producto VARCHAR(50) PRIMARY KEY,
    modelo VARCHAR(100),
    tipo_carroceria VARCHAR(50),
    fuel VARCHAR(30),
    transmision_id VARCHAR(30),
    equipamiento VARCHAR(100),
    kw NUMERIC(8,2)
);

CREATE TABLE stores (
    tienda_desc VARCHAR(150) PRIMARY KEY,
    prov_desc VARCHAR(100),
    zona VARCHAR(50)
);

CREATE TABLE model_costs (
    modelo VARCHAR(100) PRIMARY KEY,
    margen NUMERIC(12,2),
    coste_transporte NUMERIC(12,2),
    margen_distribuidor NUMERIC(12,2),
    gastos_marketing NUMERIC(12,2),
    mantenimiento_medio NUMERIC(12,2),
    comision_marca NUMERIC(12,2)
);

CREATE TABLE sales (
    code VARCHAR(50) PRIMARY KEY,
    sales_date DATE,
    customer_id INTEGER REFERENCES customers(customer_id),
    id_producto VARCHAR(50) REFERENCES products(id_producto),
    tienda_desc VARCHAR(150) REFERENCES stores(tienda_desc),
    pvp NUMERIC(12,2),
    motivo_venta VARCHAR(100),
    forma_pago VARCHAR(50),
    coste_venta_no_impuestos NUMERIC(12,2),
    margen_eur_bruto NUMERIC(12,2),
    margen_eur NUMERIC(12,2),
    origen VARCHAR(50),
    extension_garantia VARCHAR(20),
    seguro_bateria_largo_plazo VARCHAR(10),
    mantenimiento_gratuito VARCHAR(10),
    fin_garantia DATE,
    base_date DATE,
    en_garantia VARCHAR(10),
    revisiones INTEGER,
    km_medio_por_revision NUMERIC(10,2),
    km_ultima_revision NUMERIC(10,2),
    encuesta_cliente_zona_taller NUMERIC(5,2),
    queja VARCHAR(10),
    lead_compra INTEGER,
    days_last_service INTEGER,
    fue_lead INTEGER,
    churn_400 VARCHAR(5)
);

CREATE TABLE new_sales (
    code VARCHAR(50) PRIMARY KEY,
    sales_date DATE,
    customer_id INTEGER REFERENCES customers(customer_id),
    id_producto VARCHAR(50) REFERENCES products(id_producto),
    tienda_desc VARCHAR(150) REFERENCES stores(tienda_desc),
    pvp NUMERIC(12,2),
    motivo_venta VARCHAR(100),
    forma_pago VARCHAR(50),
    coste_venta_no_impuestos NUMERIC(12,2),
    margen_eur_bruto NUMERIC(12,2),
    margen_eur NUMERIC(12,2),
    origen VARCHAR(50),
    extension_garantia VARCHAR(20),
    seguro_bateria_largo_plazo VARCHAR(10),
    mantenimiento_gratuito VARCHAR(10),
    fin_garantia DATE,
    base_date DATE,
    en_garantia VARCHAR(10),
    revisiones INTEGER,
    km_medio_por_revision NUMERIC(10,2),
    km_ultima_revision NUMERIC(10,2),
    encuesta_cliente_zona_taller NUMERIC(5,2),
    queja VARCHAR(10),
    lead_compra INTEGER,
    lead_compra_1 INTEGER
);

CREATE INDEX idx_sales_customer ON sales(customer_id);
CREATE INDEX idx_sales_product ON sales(id_producto);
CREATE INDEX idx_sales_store ON sales(tienda_desc);
CREATE INDEX idx_sales_modelo ON sales(churn_400);
CREATE INDEX idx_sales_date ON sales(sales_date);
CREATE INDEX idx_nsales_customer ON new_sales(customer_id);
CREATE INDEX idx_nsales_product ON new_sales(id_producto)

In [6]:
date_cols = ['Sales_Date', 'FIN_GARANTIA', 'BASE_DATE']

for col in date_cols:
    customer_data[col] = pd.to_datetime(customer_data[col], format='%d/%m/%Y', errors='coerce')
    new_customer[col] = pd.to_datetime(new_customer[col], format='%d/%m/%Y', errors='coerce')

print("✅ Fechas parseadas")

✅ Fechas parseadas

In [7]:
customer_cols = ['Customer_ID', 'GENERO', 'CODIGO_POSTAL', 'Edad', 'RENTA_MEDIA_ESTIMADA', 'STATUS_SOCIAL']

df_customers = pd.concat([
    customer_data[customer_cols],
    new_customer[customer_cols]
]).drop_duplicates(subset='Customer_ID')

df_customers.columns = ['customer_id', 'genero', 'codigo_postal', 'edad', 'renta_media_estimada', 'status_social']

agent.append_to_postgres(df_customers, 'customers')
print(f"✅ customers: {len(df_customers)} registros")

✅ customers: 52553 registros

In [8]:
product_cols = ['Id_Producto', 'Modelo', 'TIPO_CARROCERIA', 'Fuel', 'TRANSMISION_ID', 'Equipamiento', 'Kw']

df_products = pd.concat([
    customer_data[product_cols],
    new_customer[product_cols]
]).drop_duplicates(subset='Id_Producto')

df_products.columns = ['id_producto', 'modelo', 'tipo_carroceria', 'fuel', 'transmision_id', 'equipamiento', 'kw']

agent.append_to_postgres(df_products, 'products')
print(f"✅ products: {len(df_products)} registros")

✅ products: 504 registros

In [9]:
store_cols = ['TIENDA_DESC', 'PROV_DESC', 'ZONA']

df_stores = pd.concat([
    customer_data[store_cols],
    new_customer[store_cols]
]).drop_duplicates(subset='TIENDA_DESC')

df_stores.columns = ['tienda_desc', 'prov_desc', 'zona']

agent.append_to_postgres(df_stores, 'stores')
print(f"✅ stores: {len(df_stores)} registros")

✅ stores: 12 registros

In [10]:
df_costs = cost.copy()
df_costs.columns = ['modelo', 'margen', 'coste_transporte', 'margen_distribuidor',
                     'gastos_marketing', 'mantenimiento_medio', 'comision_marca']

agent.append_to_postgres(df_costs, 'model_costs')
print(f"✅ model_costs: {len(df_costs)} registros")

✅ model_costs: 11 registros

In [11]:
df_sales = customer_data.rename(columns={
    'CODE': 'code', 'Sales_Date': 'sales_date', 'Customer_ID': 'customer_id',
    'Id_Producto': 'id_producto', 'TIENDA_DESC': 'tienda_desc',
    'PVP': 'pvp', 'MOTIVO_VENTA': 'motivo_venta', 'FORMA_PAGO': 'forma_pago',
    'COSTE_VENTA_NO_IMPUESTOS': 'coste_venta_no_impuestos',
    'Margen_eur_bruto': 'margen_eur_bruto', 'Margen_eur': 'margen_eur',
    'Origen': 'origen', 'EXTENSION_GARANTIA': 'extension_garantia',
    'SEGURO_BATERIA_LARGO_PLAZO': 'seguro_bateria_largo_plazo',
    'MANTENIMIENTO_GRATUITO': 'mantenimiento_gratuito',
    'FIN_GARANTIA': 'fin_garantia', 'BASE_DATE': 'base_date',
    'EN_GARANTIA': 'en_garantia', 'Revisiones': 'revisiones',
    'Km_medio_por_revision': 'km_medio_por_revision',
    'km_ultima_revision': 'km_ultima_revision',
    'ENCUESTA_CLIENTE_ZONA_TALLER': 'encuesta_cliente_zona_taller',
    'QUEJA': 'queja', 'Lead_compra': 'lead_compra',
    'DAYS_LAST_SERVICE': 'days_last_service', 'Fue_Lead': 'fue_lead',
    'Churn_400': 'churn_400'
})

# Seleccionar solo las columnas de la tabla
sales_cols = ['code', 'sales_date', 'customer_id', 'id_producto', 'tienda_desc',
              'pvp', 'motivo_venta', 'forma_pago', 'coste_venta_no_impuestos',
              'margen_eur_bruto', 'margen_eur', 'origen', 'extension_garantia',
              'seguro_bateria_largo_plazo', 'mantenimiento_gratuito',
              'fin_garantia', 'base_date', 'en_garantia', 'revisiones',
              'km_medio_por_revision', 'km_ultima_revision',
              'encuesta_cliente_zona_taller', 'queja', 'lead_compra',
              'days_last_service', 'fue_lead', 'churn_400']

agent.append_to_postgres(df_sales[sales_cols], 'sales')
print(f"✅ sales (train): {len(df_sales)} registros")

✅ sales (train): 58049 registros

In [12]:
df_new = new_customer.rename(columns={
    'CODE': 'code', 'Sales_Date': 'sales_date', 'Customer_ID': 'customer_id',
    'Id_Producto': 'id_producto', 'TIENDA_DESC': 'tienda_desc',
    'PVP': 'pvp', 'MOTIVO_VENTA': 'motivo_venta', 'FORMA_PAGO': 'forma_pago',
    'COSTE_VENTA_NO_IMPUESTOS': 'coste_venta_no_impuestos',
    'Margen_eur_bruto': 'margen_eur_bruto', 'Margen_eur': 'margen_eur',
    'Origen': 'origen', 'EXTENSION_GARANTIA': 'extension_garantia',
    'SEGURO_BATERIA_LARGO_PLAZO': 'seguro_bateria_largo_plazo',
    'MANTENIMIENTO_GRATUITO': 'mantenimiento_gratuito',
    'FIN_GARANTIA': 'fin_garantia', 'BASE_DATE': 'base_date',
    'EN_GARANTIA': 'en_garantia', 'Revisiones': 'revisiones',
    'Km_medio_por_revision': 'km_medio_por_revision',
    'km_ultima_revision': 'km_ultima_revision',
    'ENCUESTA_CLIENTE_ZONA_TALLER': 'encuesta_cliente_zona_taller',
    'QUEJA': 'queja', 'Lead_compra': 'lead_compra',
    'Lead_compra_1': 'lead_compra_1'
})

new_sales_cols = ['code', 'sales_date', 'customer_id', 'id_producto', 'tienda_desc',
                  'pvp', 'motivo_venta', 'forma_pago', 'coste_venta_no_impuestos',
                  'margen_eur_bruto', 'margen_eur', 'origen', 'extension_garantia',
                  'seguro_bateria_largo_plazo', 'mantenimiento_gratuito',
                  'fin_garantia', 'base_date', 'en_garantia', 'revisiones',
                  'km_medio_por_revision', 'km_ultima_revision',
                  'encuesta_cliente_zona_taller', 'queja', 'lead_compra',
                  'lead_compra_1']

agent.append_to_postgres(df_new[new_sales_cols], 'new_sales')
print(f"✅ new_sales (validación): {len(df_new)} registros")

✅ new_sales (validación): 10000 registros

In [13]:
%%sql
SELECT 'customers' as tabla, COUNT(*) as registros FROM customers
UNION ALL SELECT 'products', COUNT(*) FROM products
UNION ALL SELECT 'stores', COUNT(*) FROM stores
UNION ALL SELECT 'model_costs', COUNT(*) FROM model_costs
UNION ALL SELECT 'sales (train)', COUNT(*) FROM sales
UNION ALL SELECT 'new_sales (val)', COUNT(*) FROM new_sales
ORDER BY registros DESC

             tabla  registros
0    sales (train)      58049
1        customers      52553
2  new_sales (val)      10000
3         products        504
4           stores         12
5      model_costs         11

In [14]:
%%sql
SELECT 'clientes sin ventas' as check,
       COUNT(*) as n
FROM customers c
WHERE NOT EXISTS (SELECT 1 FROM sales s WHERE s.customer_id = c.customer_id)
  AND NOT EXISTS (SELECT 1 FROM new_sales ns WHERE ns.customer_id = c.customer_id)
UNION ALL
SELECT 'ventas con cliente multi-compra',
       COUNT(*)
FROM (SELECT customer_id FROM sales GROUP BY customer_id HAVING COUNT(*) > 1) sub

                             check      n
0  ventas con cliente multi-compra  11562
1              clientes sin ventas      0